#ifndef PROTOCOL_CONSTANTS_H
#define PROTOCOL_CONSTANTS_H

#define MAX_FLIGHT_NUMBER 8
#define MAX_BUF_SIZE 1024
#define GET_FLIGHT_STATE 1
#define BOOK_SEAT 2
#define CANCEL_SEAT 3
#define NEW_FLIGHT 4
#define REMOVE_FLIGHT 5
#define CLOSE 6
#define MAX_CHOICE 6

#endif
