#ifndef PROTOCOL_CONSTANTS_H
#define PROTOCOL_CONSTANTS_H

#define MAX_FLIGHT_NUMBER 8
#define MAX_BUF_SIZE 1024
#define SERVER_PORT 1049
#define RESPONSE_OK 0
#define RESPONSE_ERROR -1
#define CHECK_CONNECTION 10
#define GET_FLIGHT_STATE 1
#define BOOK_SEAT 2
#define CANCEL_SEAT 3
#define NEW_FLIGHT 4
#define REMOVE_FLIGHT 5
#define GET_RESERVATIONS 6
#define GET_CANCELLATIONS 7
#define GET_FLIGHTS 8
#define CLOSE 9
#define MAX_CHOICE 9

//#define DEBUG_PRINTS 0

#endif
